### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Yoda-BZH** [Yoda-BZH/icinga2-formula-1#1]
```
----------
          ID: icinga2_client_cert
    Function: x509.certificate_managed
        Name: /var/lib/icinga2/$HOSTNAME.crt
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2106, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/x509.py", line 674, in certificate_managed
                  name, days_remaining, append_certs, **kwargs
                File "/usr/lib/python3/dist-packages/salt/states/x509.py", line 504, in _certificate_is_valid
                  testrun=True, **cert_spec
                File "/var/cache/salt/minion/extmods/modules/x509.py", line 1373, in create_certificate
                  passphrase=kwargs['public_key_passphrase']).replace('\n', '')
              TypeError: a bytes-like object is required, not 'str'
     Started: 11:48:12.720799
    Duration: 7.279 ms
     Changes:   
```

using python3.7
debian 10
salt 3002.6

**Comment by Yoda-BZH** [comment]
using pillarstack, using: 
```
states:
  list:
    - icinga2.master

icinga2:
  lookup:
    master_fqdn: example.tld
    master_minion_id: example.tld
    constants:
      TicketSalt: <insert here salt ticket>

    features:
      api:
        ca_path: /var/lib/icinga2/ca/ca.crt
    plugins:
      - itl
      - plugins
      - plugins-contrib
    conf:
      apiuser:
        root:
          password: apirootpassword
          permissions:
            - '*'
```

**Comment by hemebond** [comment]
Seems to be the same issue here https://github.com/saltstack/salt/issues/53316

**Comment by Yoda-BZH** [comment]
and waiting for https://github.com/saltstack/salt/pull/52014
